/**
 * The settings panel, mounted into the shell's `settings.section` slot.
 *
 * The plugin renders nothing else on the page — the pet itself lives in the
 * desktop app — so this panel is the plugin's only visible surface: which pet
 * shows on the desktop, its name, and the companion bridge switch. Every
 * control writes straight into the {@link PetSettingsStore}, which notifies
 * subscribers (the bridge included) so changes take effect with no "save"
 * step, and the store's dual-backend write makes them stick. The picker
 * previews each pet in the affection pose (`pet`), because that is the pose
 * that best distinguishes the sprites at thumbnail size.
 *
 * @module @seaveyon/dsh-pet/client/settings-panel
 */

import { useCallback, useEffect, useSyncExternalStore } from 'react'
import type { DesktopPet } from './bridge.js'
import { type DesktopPetsStore, prettifyImportedPetId } from './desktop-pets.js'
import { detectLocale, getStrings } from './i18n.js'
import { PET_STYLE_CSS, PETS } from './pets.js'
import { RasterPet } from './raster-pet.js'
import type { PetSettingsStore } from './settings.js'

export interface PetSettingsPanelProps {
  settings: PetSettingsStore
  /**
   * Imported-pet discovery. Absent in tests and minimal mounts: only the
   * built-in roster shows and no fetch is attempted.
   */
  desktopPets?: DesktopPetsStore
}

const rowStyle = {
  display: 'flex',
  alignItems: 'center',
  gap: '8px',
  marginBlock: '8px',
} as const

const NO_IMPORTED_PETS: readonly DesktopPet[] = []
const NOOP_SUBSCRIBE = () => () => {}

/** The picker's tile is 56px with a 2px border; the preview gets the rest. */
const PREVIEW_SIZE = 52

export function PetSettingsPanel({ settings, desktopPets }: PetSettingsPanelProps) {
  const strings = getStrings()
  const locale = detectLocale(navigator.language)
  const config = useSyncExternalStore(settings.subscribe, settings.getSnapshot)
  const subscribeImported = useCallback(
    (listener: () => void) => desktopPets?.subscribe(listener) ?? NOOP_SUBSCRIBE(),
    [desktopPets],
  )
  const getImportedSnapshot = useCallback(
    () => desktopPets?.getSnapshot() ?? NO_IMPORTED_PETS,
    [desktopPets],
  )
  const importedPets = useSyncExternalStore(subscribeImported, getImportedSnapshot)

  // Opening the panel is the discovery moment: the desktop app is the kind of
  // thing users start right before importing a pet, so ask again every mount.
  useEffect(() => {
    void desktopPets?.refresh()
  }, [desktopPets])

  return (
    <section aria-label={strings.settingsSection}>
      {/* The built-in previews' keyframes; the raster previews carry their own. */}
      <style>{PET_STYLE_CSS}</style>
      <p style={{ marginBlock: '8px', opacity: 0.75 }}>{strings.desktopHint}</p>
      <div
        role="group"
        aria-label={strings.appearanceLabel}
        style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}
      >
        {PETS.map((pet) => (
          <button
            key={pet.id}
            type="button"
            title={pet.label[locale]}
            aria-pressed={config.petId === pet.id}
            onClick={() => settings.update({ petId: pet.id })}
            style={{
              width: '56px',
              height: '56px',
              borderRadius: '10px',
              cursor: 'pointer',
              border:
                config.petId === pet.id
                  ? '2px solid var(--dsw-color-primary, #4b6bfb)'
                  : '2px solid transparent',
              background: 'var(--dsw-color-surface, #f3f4f6)',
            }}
            // Sprite markup is generated by pets.ts, never from user data.
            // biome-ignore lint/security/noDangerouslySetInnerHtml: see pets.ts
            dangerouslySetInnerHTML={{ __html: pet.svg(config.petId === pet.id ? 'pet' : 'idle') }}
          />
        ))}
        {importedPets.map((pet) => (
          <button
            key={pet.id}
            type="button"
            title={prettifyImportedPetId(pet.id)}
            aria-pressed={config.petId === pet.id}
            onClick={() => settings.update({ petId: pet.id })}
            style={{
              position: 'relative',
              width: '56px',
              height: '56px',
              padding: 0,
              borderRadius: '10px',
              cursor: 'pointer',
              border:
                config.petId === pet.id
                  ? '2px solid var(--dsw-color-primary, #4b6bfb)'
                  : '2px solid transparent',
              background: 'var(--dsw-color-surface, #f3f4f6)',
              overflow: 'hidden',
            }}
          >
            {/* Same pose rule as the built-ins: affection when selected. */}
            <RasterPet
              pet={pet}
              mood={config.petId === pet.id ? 'pet' : 'idle'}
              size={PREVIEW_SIZE}
            />
            <span
              style={{
                position: 'absolute',
                right: '2px',
                bottom: '2px',
                padding: '0 4px',
                borderRadius: '6px',
                fontSize: '9px',
                lineHeight: '14px',
                background: 'var(--dsw-color-primary, #4b6bfb)',
                color: 'var(--dsw-color-surface, #fff)',
                pointerEvents: 'none',
              }}
            >
              {strings.desktopPetBadge}
            </span>
          </button>
        ))}
      </div>
      <label style={rowStyle}>
        {strings.nameLabel}
        <input
          type="text"
          value={config.name}
          onChange={(event) => settings.update({ name: event.target.value })}
        />
      </label>
      <label style={rowStyle}>
        {strings.companionLabel}
        <input
          type="checkbox"
          checked={config.companionEnabled}
          onChange={(event) => settings.update({ companionEnabled: event.target.checked })}
        />
      </label>
    </section>
  )
}
