/**
 * The settings panel, mounted into the shell's `settings.section` slot.
 *
 * Every control writes straight into the {@link PetSettingsStore}, which
 * notifies subscribers — the overlay included — so changes take effect with
 * no "save" step, and the store's dual-backend write makes them stick. The
 * picker previews each pet in the affection pose (`pet`), because that is the
 * pose that best distinguishes the sprites at thumbnail size.
 *
 * @module @seaveyon/dsh-pet/client/settings-panel
 */

import { useSyncExternalStore } from 'react'
import { detectLocale, getStrings } from './i18n.js'
import { PETS } from './pets.js'
import { MAX_SCALE, MIN_SCALE, type PetSettingsStore } from './settings.js'

export interface PetSettingsPanelProps {
  settings: PetSettingsStore
}

const rowStyle = {
  display: 'flex',
  alignItems: 'center',
  gap: '8px',
  marginBlock: '8px',
} as const

export function PetSettingsPanel({ settings }: PetSettingsPanelProps) {
  const strings = getStrings()
  const locale = detectLocale(navigator.language)
  const config = useSyncExternalStore(settings.subscribe, settings.getSnapshot)

  return (
    <section aria-label={strings.settingsSection}>
      <div
        role="group"
        aria-label={strings.appearanceLabel}
        style={{ display: 'flex', gap: '8px' }}
      >
        {PETS.map((pet) => (
          <button
            key={pet.id}
            type="button"
            title={pet.label[locale]}
            aria-pressed={config.petId === pet.id}
            onClick={() => settings.update({ petId: pet.id })}
            style={{
              width: '56px',
              height: '56px',
              borderRadius: '10px',
              cursor: 'pointer',
              border:
                config.petId === pet.id
                  ? '2px solid var(--dsw-color-primary, #4b6bfb)'
                  : '2px solid transparent',
              background: 'var(--dsw-color-surface, #f3f4f6)',
            }}
            // Sprite markup is generated by pets.ts, never from user data.
            // biome-ignore lint/security/noDangerouslySetInnerHtml: see pets.ts
            dangerouslySetInnerHTML={{ __html: pet.svg(config.petId === pet.id ? 'pet' : 'idle') }}
          />
        ))}
      </div>
      <label style={rowStyle}>
        {strings.nameLabel}
        <input
          type="text"
          value={config.name}
          onChange={(event) => settings.update({ name: event.target.value })}
        />
      </label>
      <label style={rowStyle}>
        {strings.scaleLabel}
        <input
          type="range"
          min={MIN_SCALE}
          max={MAX_SCALE}
          step={0.1}
          value={config.scale}
          onChange={(event) => settings.update({ scale: Number(event.target.value) })}
        />
        <span>{config.scale.toFixed(1)}×</span>
      </label>
      <label style={rowStyle}>
        {strings.visibleLabel}
        <input
          type="checkbox"
          checked={config.visible}
          onChange={(event) => settings.update({ visible: event.target.checked })}
        />
      </label>
      <label style={rowStyle}>
        {strings.companionLabel}
        <input
          type="checkbox"
          checked={config.companionEnabled}
          onChange={(event) => settings.update({ companionEnabled: event.target.checked })}
        />
      </label>
    </section>
  )
}
